// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import GridController from "./grid_controller"
application.register("grid", GridController)

import DecesController from "./deces_controller"
application.register("deces", DecesController)

import SelectController from "./select_controller"
application.register("select", SelectController)
