// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import AopController from "./aop_controller"
application.register("aop", AopController)

import DecesController from "./deces_controller"
application.register("deces", DecesController)

import GridController from "./grid_controller"
application.register("grid", GridController)

import HelloController from "./hello_controller"
application.register("hello", HelloController)
